# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=1000)),
                ('report', models.CharField(max_length=1000)),
            ],
        ),
    ]
