# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='artist',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
