# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20170609_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
